version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password